name: 'jaffle_shop_metrics'

config-version: 2
version: '0.1'

profile: 'jaffle_shop_metrics'

model-paths: ["models"]
seed-paths: ["seeds"]
test-paths: ["tests"]
analysis-paths: ["analysis"]
macro-paths: ["macros"]

target-path: "target"
clean-targets:
    - "target"
    - "dbt_modules"
    - "logs"

require-dbt-version: [">=1.2.0-rc1", "<2.0.0"]

models:
  jaffle_shop_metrics:
      materialized: table
      staging:
        materialized: view

  # ad_reporting:
  #   +schema:

  # apple_search_ads:
  #   +schema:
  # apple_search_ads_source:
  #   +schema:
  
  # facebook_ads:
  #   +schema:
  # facebook_ads_source:
  #   +schema:
  
  # google_ads:
  #   +schema:
  # google_ads_source:
  #   +schema:

  # linkedin:
  #   +schema:
  # linkedin_source:
  #   +schema:

  # microsoft_ads:
  #   +schema:
  # microsoft_ads_source:
  #   +schema:

  # pinterest:
  #   +schema:
  # pinterest_source:
  #   +schema:
  
  # twitter_ads:
  #   +schema:
  # twitter_ads_source:
  #   +schema:
  
  # snapchat_ads:
  #   +schema:
  # snapchat_ads_source:
  #   +schema:
  
  # tiktok_ads:
  #   +schema:
  # tiktok_ads_source:
  #   +schema:

vars: 
  apple_search_ads__using_search_terms: True
  twitter_ads__using_keywords: True
  apple_search_ads_source:
    apple_search_ads_schema: ad_reporting_integration_tests_v1
    apple_search_ads_organization_identifier: "apple_search_organization_data"
    apple_search_ads_campaign_history_identifier: "apple_search_campaign_history_data"
    apple_search_ads_campaign_report_identifier: "apple_search_campaign_report_data"
    apple_search_ads_ad_group_history_identifier: "apple_search_ad_group_history_data"
    apple_search_ads_ad_group_report_identifier: "apple_search_ad_group_report_data"
    apple_search_ads_ad_history_identifier: "apple_search_ad_history_data"
    apple_search_ads_ad_report_identifier: "apple_search_ad_report_data"
    apple_search_ads_keyword_history_identifier: "apple_search_keyword_history_data"
    apple_search_ads_keyword_report_identifier: "apple_search_keyword_report_data"
    apple_search_ads_search_term_report_identifier: "apple_search_search_term_report_data"
    
  google_ads_source:
    google_ads_schema: ad_reporting_integration_tests_v1
    google_ads_ad_stats_identifier: "google_ads_ad_stats_data"
    google_ads_ad_history_identifier: "google_ads_ad_history_data"
    google_ads_ad_group_history_identifier: "google_ads_ad_group_history_data"
    google_ads_campaign_history_identifier: "google_ads_campaign_history_data"
    google_ads_account_history_identifier: "google_ads_account_history_data"
    google_ads_keyword_stats_identifier: "google_ads_keyword_stats_data"
    google_ads_account_stats_identifier: "google_ads_account_stats_data"
    google_ads_ad_group_stats_identifier: "google_ads_ad_group_stats_data"
    google_ads_campaign_stats_identifier: "google_ads_campaign_stats_data"
    google_ads_ad_group_criterion_history_identifier: "google_ads_ad_group_criterion_history_data"

  microsoft_ads_source:
    microsoft_ads_schema: ad_reporting_integration_tests_v1
    microsoft_ads_account_history_identifier: "microsoft_ads_account_history_data"
    microsoft_ads_account_daily_report_identifier: "microsoft_ads_account_performance_daily_report_data"
    microsoft_ads_ad_group_history_identifier: "microsoft_ads_ad_group_history_data"
    microsoft_ads_ad_group_daily_report_identifier: "microsoft_ads_ad_group_performance_daily_report_data"
    microsoft_ads_ad_history_identifier: "microsoft_ads_ad_history_data"
    microsoft_ads_ad_daily_report_identifier: "microsoft_ads_ad_performance_daily_report_data"
    microsoft_ads_campaign_history_identifier: "microsoft_ads_campaign_history_data"
    microsoft_ads_campaign_daily_report_identifier: "microsoft_ads_campaign_performance_daily_report_data"
    microsoft_ads_keyword_history_identifier: "microsoft_ads_keyword_history_data"
    microsoft_ads_keyword_daily_report_identifier: "microsoft_ads_keyword_performance_daily_report_data"
    microsoft_ads_search_daily_report_identifier: "microsoft_ads_search_performance_daily_report_data"

  linkedin_source:
    linkedin_ads_schema: ad_reporting_integration_tests_v1
    linkedin_ads_account_history_identifier: "linkedin_ad_account_history_data"
    linkedin_ads_ad_analytics_by_creative_identifier: "linkedin_ad_analytics_by_creative_data"
    linkedin_ads_campaign_group_history_identifier: "linkedin_ad_campaign_group_history_data"
    linkedin_ads_campaign_history_identifier: "linkedin_ad_campaign_history_data"
    linkedin_ads_creative_history_identifier: "linkedin_ad_creative_history_data"
    linkedin_ads_ad_analytics_by_campaign_identifier: "linkedin_ad_analytics_by_campaign_data"

  twitter_ads_source:
    twitter_ads_schema: ad_reporting_integration_tests_v1
    twitter_ads_account_history_identifier: "twitter_account_history_data"
    twitter_ads_campaign_history_identifier: "twitter_campaign_history_data"
    twitter_ads_line_item_history_identifier: "twitter_line_item_history_data"
    twitter_ads_promoted_tweet_history_identifier: "twitter_promoted_tweet_history_data"
    twitter_ads_promoted_tweet_report_identifier: "twitter_promoted_tweet_report_data"
    twitter_ads_tweet_url_identifier: "twitter_tweet_url_data"
    twitter_ads_tweet_identifier: "twitter_tweet_data"
    twitter_ads_campaign_report_identifier: "twitter_campaign_report_data"
    twitter_ads_line_item_report_identifier: "twitter_line_item_report_data"
    twitter_ads_account_report_identifier: "twitter_account_report_data"
    twitter_ads_line_item_keywords_report_identifier: "twitter_line_item_keywords_report_data"

  pinterest_source:
    pinterest_schema: ad_reporting_integration_tests_v1
    pinterest_ad_group_history_identifier: "pinterest_ads_ad_group_history_data"
    pinterest_campaign_history_identifier: "pinterest_ads_campaign_history_data"
    pinterest_pin_promotion_history_identifier: "pinterest_ads_pin_promotion_history_data"
    pinterest_pin_promotion_report_identifier: "pinterest_ads_pin_promotion_report_data"
    pinterest_keyword_history_identifier: "pinterest_ads_keyword_history_data"
    pinterest_keyword_report_identifier: "pinterest_ads_keyword_report_data"
    pinterest_ad_group_report_identifier: "pinterest_ads_ad_group_report_data"
    pinterest_campaign_report_identifier: "pinterest_ads_campaign_report_data"
    pinterest_advertiser_history_identifier: "pinterest_ads_advertiser_history_data"
    pinterest_advertiser_report_identifier: "pinterest_ads_advertiser_report_data"
    
  facebook_ads_source:
    facebook_ads_schema: ad_reporting_integration_tests_v1
    facebook_ads_account_history_identifier: "facebook_ads_account_history_data"
    facebook_ads_ad_history_identifier: "facebook_ads_ad_history_data"
    facebook_ads_ad_set_history_identifier: "facebook_ads_ad_set_history_data"
    facebook_ads_basic_ad_identifier: "facebook_ads_basic_ad_data"
    facebook_ads_campaign_history_identifier: "facebook_ads_campaign_history_data"
    facebook_ads_creative_history_identifier: "facebook_ads_creative_history_data"

  snapchat_ads_source:
    snapchat_ads_schema: ad_reporting_integration_tests_v1
    snapchat_ads_ad_account_history_identifier:  "snapchat_ad_account_history_data"
    snapchat_ads_ad_history_identifier: "snapchat_ad_history_data"
    snapchat_ads_ad_hourly_report_identifier: "snapchat_ad_hourly_report_data"
    snapchat_ads_ad_squad_history_identifier: "snapchat_ad_squad_history_data"
    snapchat_ads_ad_squad_hourly_report_identifier: "snapchat_ad_squad_hourly_report_data"
    snapchat_ads_campaign_history_identifier: "snapchat_campaign_history_data"
    snapchat_ads_campaign_hourly_report_identifier: "snapchat_campaign_hourly_report_data"
    snapchat_ads_creative_history_identifier: "snapchat_creative_history_data"
    snapchat_ads_creative_url_tag_history_identifier: "snapchat_creative_url_tag_history_data"

  tiktok_ads_source:
    tiktok_ads_schema: ad_reporting_integration_tests_v1
    tiktok_ads__ad_group_history_identifier: "tiktok_adgroup_history_data"
    tiktok_ads__ad_history_identifier: "tiktok_ad_history_data"
    tiktok_ads__advertiser_identifier: "tiktok_advertiser_data"
    tiktok_ads__campaign_history_identifier: "tiktok_campaign_history_data"
    tiktok_ads__ad_report_hourly_identifier: "tiktok_ad_report_hourly_data"
    tiktok_ads__ad_group_report_hourly_identifier: "tiktok_adgroup_report_hourly_data"
    tiktok_ads__campaign_report_hourly_identifier: "tiktok_campaign_report_hourly_data"