name: 'jaffle_shop_metrics'

config-version: 2
version: '0.1'

profile: 'jaffle_shop_metrics'

model-paths: ["models"]
seed-paths: ["seeds"]
test-paths: ["tests"]
analysis-paths: ["analysis"]
macro-paths: ["macros"]

target-path: "target"
clean-targets:
    - "target"
    - "dbt_modules"
    - "logs"

require-dbt-version: [">=1.2.0-rc1", "<2.0.0"]

models:
  jaffle_shop_metrics:
      materialized: table
      staging:
        materialized: view

vars: # remove after setting up connectors in snowflake
  apple_search_ads_schema: ad_reporting_seeds
  facebook_ads_schema: ad_reporting_seeds
  google_ads_schema: ad_reporting_seeds
  microsoft_ads_schema: ad_reporting_seeds
  linkedin_schema: ad_reporting_seeds 
  pinterest_schema: ad_reporting_seeds
  twitter_ads_schema: ad_reporting_seeds
  snapchat_schema: ad_reporting_seeds
  tiktok_ads_schema: ad_reporting_seeds